project:
  type: website

website:
  title: "Rodrigo Kersten"
  navbar:
    left:
      - href: morfo.qmd
        text: "Morfologia"
        icon: leaf
      - href: algas.qmd
        text: "Algas&Fungos"
        icon: slack
      - href: brio.qmd
        text: "Cript칩gamas"
        icon: incognito
      - href: fanero.qmd
        text: "Faner칩gamas"
        icon: flower3
      - href: invent.qmd
        text: "Invent치rio"
        icon: tree-fill
      - href: restaura.qmd
        text: "Restaura칞칚o"
        icon: image-alt

  sidebar:
    style: "docked"
    title: "Invent치rio"
    contents:
      - section: "Excel"    
        contents:
          - text: "An치lises em Excel"
            href: excel.qmd
      - section: "Utilizando o R"
        contents:
          - text: "Instalando o R"
            href: insta.qmd
          - text: "Introdu칞칚o ao R"
            href: intro.qmd
      - section: "An치lises em R"
        contents:
          - text: "Dendrograma"
            href: dendro.qmd
          - text: "Acumula칞칚o"
            href: acumula.qmd 
          - text: "칈ndices de Diversidade"
            href: diversidade.qmd
          - text: "Fitossociologia"
            href: fitos.qmd 
          - text: "Perfi da Vegeta칞칚o"
            href: perfil.qmd
          - text: "Gr치ficos IVI"
            href: ivi.qmd 
      - "---"
      - text: "游댗 Voltar"
        href: invent.qmd